name: Send Valorant Stats to TRMNL hourly
env:
  valorant_api_key: ${{ secrets.ValorantApiKey }}
  trmnl_plugin_id1: ${{ secrets.TRMNL_PLUGIN_ID1 }}
  trmnl_plugin_id2: ${{ secrets.TRMNL_PLUGIN_ID2 }}
  valorant_username1: ${{ vars.VALORANT_USERNAME1 }}
  valorant_username2: ${{ vars.VALORANT_USERNAME2  }}
  valorant_tagline1: ${{ vars.VALORANT_TAGLINE1 }}
  valorant_tagline2: ${{ vars.VALORANT_TAGLINE2  }}
on: 
  schedule:
  - cron: '0 23,0-7 * * *'
  workflow_dispatch:
jobs:     
  run-script:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script for user 1
      if: ${{ env.trmnl_plugin_id1 && env.valorant_username1 && env.valorant_tagline1 }}
      run: .\TRMNL\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:trmnl_plugin_id1" -APIKey "$env:valorant_api_key" -username $env:valorant_username1 -tagline "$env:valorant_tagline1" > $null
      shell: pwsh

    - name: Run PowerShell script for user 2
      if: ${{ env.trmnl_plugin_id2 && env.valorant_username2 && env.valorant_tagline2 }}
      run: .\TRMNL\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:trmnl_plugin_id2" -APIKey "$env:valorant_api_key" -username $env:valorant_username2  -tagline "$env:valorant_tagline2" > $null
      shell: pwsh
