name: Send Valorant Stats to TRMNL hourly
env:
  valorant_api_key: ${{ secrets.ValorantApiKey }}
  mark_trmnl_plugin_id: ${{ secrets.MARK_TRMNL_PLUGIN_ID }}
  jess_trmnl_plugin_id: ${{ secrets.JESS_TRMNL_PLUGIN_ID }}
on: 
  schedule: 
  - cron: '0 23-7 * * *'
jobs:     
  run-script:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: .\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:mark_trmnl_plugin_id" -APIKey "$env:valorant_api_key" -username "sharky big time" -tagline "bossy"
      shell: pwsh

    - name: Run PowerShell script
      run: .\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:jess_trmnl_plugin_id" -APIKey "$env:valorant_api_key" -username "BirdsNestChicago" -tagline "wingy"
      shell: pwsh
