name: Send Valorant Stats to TRMNL hourly
env:
  valorant_api_key: ${{ secrets.ValorantApiKey }}
  plugin_id: ${{ secrets.Mark_Trmnl_Plugin_Id }}
on: 
  schedule: 
  - cron: '0 * * * *'
jobs:     
  run-script:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: .\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:plugin_id" -APIKey "$env:valorant_api_key" -username "sharky big time" -tagline "bossy"
      shell: pwsh
