name: Send Valorant Stats to TRMNL hourly
env:
  valorant_api_key: ${{ secrets.ValorantApiKey }}
  trmnl_plugin_id1: ${{ secrets.TRMNL_PLUGIN_ID1 }}
  trmnl_plugin_id2: ${{ secrets.TRMNL_PLUGIN_ID2 }}
on: 
  schedule:
  - cron: '0 23,0-7 * * *'
  workflow_dispatch:
jobs:     
  run-script:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: .\TRMNL\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:trmnl_plugin_id1" -APIKey "$env:valorant_api_key" -username "$var.VALORANT_USERNAME1" -tagline "$VALORANT_TAGLINE1" > $null
      shell: pwsh

    - name: Run PowerShell script
      run: .\TRMNL\Trmnl_ValorantTracker.ps1 -TrmnlPluginId "$env:trmnl_plugin_id2" -APIKey "$env:valorant_api_key" -username "vars.$VALORANT_USERNAME2"  -tagline "$VALORANT_TAGLINE2"  > $null
      shell: pwsh
